version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: poliom_redis_prod
    restart: always
    volumes:
      - redis_data_prod:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16.2-alpine
    container_name: poliom_postgres_prod
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin_panel:
    build:
      context: .
      dockerfile: services/admin-panel/Dockerfile
    container_name: poliom_admin_panel_prod
    restart: always
    volumes:
      - ./services/admin-panel:/app
      - static_volume_prod:/app/static
      - media_volume_prod:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: .
      dockerfile: services/celery-worker/Dockerfile
    container_name: poliom_celery_worker_prod
    restart: always
    volumes:
      - ./services/celery-worker:/app
      - ./services/shared:/app/shared
      - ./uploads:/app/uploads
    env_file:
      - .env.prod
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  telegram-bot:
    build:
      context: .
      dockerfile: services/telegram-bot/Dockerfile
    container_name: poliom_telegram_bot_prod
    restart: always
    volumes:
      - ./services/telegram-bot:/app
      - ./services/shared:/app/shared
      - ./uploads:/app/uploads
    env_file:
      - .env.prod
    depends_on:
      admin_panel:
        condition: service_started
      celery_worker:
        condition: service_started

volumes:
  postgres_data_prod:
  redis_data_prod:
  static_volume_prod:
  media_volume_prod:

networks:
  default:
    name: poliom_network_prod 